import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import useUrlHash from '../hooks/useUrlHash'
import styles from '../styles/Home.module.css'
import Navbar from '../ui/Navbar/Navbar'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className='md:ml-24'>
         <section id="home" className="bg-red-400 min-h-screen">home</section>
         <section id="about" className="min-h-screen bg-blue-400">about</section>
         <section id="experience" className="min-h-screen bg-green-400">experience</section>
         <section id="skills" className="min-h-screen bg-yellow-400">skills</section>
      </main>
      
    </div>
  )
}

export default Home
